### ISSUE TITLE
Android Platform CTS test pass issue

### ISSUE THREAD

**Issue by Lagrange1027** [KhronosGroup/OpenXR-CTS#24]
Hi，dear Ryan A. Pavlik ：
  I have developed my openxr runtime on android platform.And  when i try pass the cts test,i have encounted a problem .
my problem is that:  In my runtime i try to get the ANativeWindow by  activity.getwindow.takesurface(callback) like NaitveActivity and that result to the NaitveActivity  can not get the ANativeWindow  any more . And with my runtime the 
 HelloXR work all fine ，but when i try to pass the cts,it dosen't wotk at all because  before run cts test, it will check whether AndroidApplicationNativeWindow is nullpointer,  the code is bellow:

```
   /// Run the actual conformance tests only when all required android components are present
    if (testThreadStarted == false && **AndroidApplicationNativeWindow != NULL**) {
        testThreadStarted = true;
        androidTestThread = std::thread([&]() {
            ATTACH_THREAD;
            ALOGV("... begin conformance test ...");
```
I find the AndroidApplicationNativeWindow hasn't been used in HelloXR and CTS at all , dose the nullpointer check really need before cts test? I look forward to your reply ,thanks!

**Comment by Lagrange1027** [comment]
Hi,rpavlik:
I look forward to your reply ，thanks very much！

**Comment by utzcoz** [comment]
> I find the AndroidApplicationNativeWindow hasn't been used in HelloXR and CTS at all , dose the nullpointer check really need before cts test? I look forward to your reply ,thanks!

https://github.com/KhronosGroup/OpenXR-CTS/search?q=AndroidApplicationNativeWindow Looks like this NULL checking for `AndroidApplicationNativeWinow` doesn't exist anymore.

**Comment by rpavlik** [comment]
It still appears to exist in my code here. I suspect the issue is in your runtime: you can't just take the surface, as you've noticed this breaks ANativeWindow. Does it work if you remove the null check? or does that just make it fail later?

You can look how Monado does it: we inject an additional surface, either owned by the service, or directly into the activity. I think this is probably how you have to do it.

**Comment by rpavlik** [comment]
The check for AndroidApplicationNativeWindow is to make sure that the app has fully started before the tests begin. By stealing the app's surface, the check will always fail.

**Comment by rpavlik** [comment]
The check for the native window has now been changed to accomodate systems where there is no native window allocated for XR applications. I'm pretty sure your "stealing the native window" will break some applications, but regardless, I think you'll find the latest devel branch of the CTS will work for you.
