### ISSUE TITLE
GLES plugin - 8 bit srgb instead of 8-bit linear?

### ISSUE THREAD

**Issue by rpavlik** [KhronosGroup/OpenXR-CTS#28]
Shouldn't there be a corresponding change in the GLES plugin?

_Originally posted by @pauloAndroid in https://github.com/KhronosGroup/OpenXR-CTS/issues/26#issuecomment-819080567_

**Comment by pauloAndroid** [comment]
My comment was addressed in https://github.com/KhronosGroup/OpenXR-CTS/pull/26

**Comment by rpavlik** [comment]
Ah cool, very good, thanks for following up! (I had forgotten this detail)
