### ISSUE TITLE
CTS build with Andriod error

### ISSUE THREAD

**Issue by jiegeidol** [KhronosGroup/OpenXR-CTS#3]
when I tried to compile cts with andriod env, the errors occurred as blew:

xxxx\cmake\debug\armeabi-v7a\src\conformance\conformance_layer\gen_dispatch.cpp:35:21: note: consider defining 'ConformanceLayer_xrDestroyInstance' with the 'aapcs-vfp' calling convention

![image](https://user-images.githubusercontent.com/7903848/93858579-f4574f00-fcee-11ea-9104-a4fc14bab1b3.png)

**Comment by rpavlik** [comment]
Thanks for filing this - I had found and submitted changes for the SDK solving this, but haven't done the same for the CTS. I'll port it over.

**Comment by rpavlik** [comment]
This will be fixed in the next release.
