### ISSUE TITLE
can not build with android platform

### ISSUE THREAD

**Issue by plending** [KhronosGroup/OpenXR-CTS#31]
Hi，dear Ryan A. Pavlik ：
     I have developed my openxr runtime on android platform. I want to run a CTS test, But I encounted a compile problem  which can not find "src/version.gradle" file, when I compiled the source code on android platform with android studio.
     How can I build the source code on android platform with android studio? or how can I get the file version.gradle?
     I am looking forward to your reply ,thanks!

**Comment by plending** [comment]
Hi,rpavlik:
I am looking forward to your reply ，thank you very much！

**Comment by utzcoz** [comment]
> Hi，dear Ryan A. Pavlik ： I have developed my openxr runtime on android platform. I want to run a CTS test, But I encounted a compile problem which can not find "src/version.gradle" file, when I compiled the source code on android platform with android studio. How can I build the source code on android platform with android studio? or how can I get the file version.gradle? I am looking forward to your reply ,thanks!

I remember OpenXR-SDK-Source(https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/master/src/version.gradle) has a version.gradle, maybe you can copy it and try it.

**Comment by rpavlik** [comment]
This should be buildable in the upcoming OpenXR release. There are a few more improvements for the CTS I'm waiting for WG approval to merge.
