### ISSUE TITLE
can not test on android

### ISSUE THREAD

**Issue by plending** [KhronosGroup/OpenXR-CTS#39]
Hi，dear Ryan A. Pavlik ：
I have developed my openxr runtime on android platform. 
I have build the conformance-debug.apk successfully.
But when I tye to run the CTS tests, it seems to can not run any test cases

CTS version :  ## OpenXR CTS 1.0.22.1 (Approved 2022-01-13)

which logs seems like below：

	Line 323: 05-31 13:17:27.865 31746 31779 V OpenXR_Conformance: ----------------------------------------------------------------
	Line 324: 05-31 13:17:27.865 31746 31779 V OpenXR_Conformance: android_app_entry()
	Line 325: 05-31 13:17:27.865 31746 31779 V OpenXR_Conformance:     android_main()
	Line 326: 05-31 13:17:27.865 31746 31779 V OpenXR-Loader: Verbose [GENERAL | xrInitializeLoaderKHR | OpenXR-Loader] : Entering loader trampoline
	Line 327: 05-31 13:17:27.865 31746 31779 V OpenXR_Conformance: ### Exception Test: - before throw...
	Line 328: 05-31 13:17:27.865 31746 31779 V OpenXR_Conformance: ### Exception Test: caught - `### Exception Test DONE ###`
	Line 331: 05-31 13:17:27.866 31746 31779 V OpenXR_Conformance:     APP_CMD_START
	Line 334: 05-31 13:17:27.867 31746 31779 V OpenXR_Conformance:     APP_CMD_RESUME
	Line 340: 05-31 13:17:27.874 31746 31779 V OpenXR_Conformance:     APP_CMD_INIT_WINDOW
	Line 342: 05-31 13:17:27.874 31746 31782 V OpenXR_Conformance: AttachCurrentThread
	Line 343: 05-31 13:17:27.875 31746 31782 V OpenXR_Conformance: ... begin conformance test ...
        Line 344: 05-31 13:17:27.875 31746 31782 V OpenXR_Conformance: arg[0] = OpenXR_Conformance_Test_Android
        Line 345: 05-31 13:17:27.875 31746 31782 V OpenXR_Conformance: arg[1] = -G
        Line 346: 05-31 13:17:27.875 31746 31782 V OpenXR_Conformance: arg[2] = OpenGLES
        Line 347: 05-31 13:17:27.875 31746 31782 V OpenXR_Conformance: arg[3] = -r
        Line 348: 05-31 13:17:27.875 31746 31782 V OpenXR_Conformance: arg[4] = xml
        Line 349: 05-31 13:17:27.875 31746 31782 V OpenXR_Conformance: arg[5] = -o
        Line 350: 05-31 13:17:27.875 31746 31782 V OpenXR_Conformance: arg[6] = /sdcard/openxr_conformance.xml
	Line 354: 05-31 13:17:27.877 31746 31782 V OpenXR_Conformance: *********************************************
	Line 355: 05-31 13:17:27.877 31746 31782 V OpenXR_Conformance: OpenXR Conformance Test v1.0.23
	Line 356: 05-31 13:17:27.877 31746 31782 V OpenXR_Conformance: *********************************************
	Line 359: 05-31 13:17:27.878 31746 31782 V OpenXR_Conformance: AndroidApplicationVM = 0x77b78de380
	Line 360: 05-31 13:17:27.878 31746 31782 V OpenXR_Conformance: AndroidApplicationActivity = 0x26a6
	Line 363: 05-31 13:17:27.878 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrEnumerateApiLayerProperties | OpenXR-Loader] : Entering loader trampoline
	Line 365: 05-31 13:17:27.878 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Entering loader trampoline
	Line 374: 05-31 13:17:27.880 31746 31782 I OpenXR-Loader: Info [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - using global runtime file /system/active_runtime.json
	Line 375: 05-31 13:17:27.880 31746 31782 I OpenXR-Loader: Info [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::CreateIfValid - attempting to load /system/active_runtime.json
	Line 391: 05-31 13:17:27.888 31746 31782 I OpenXR-Loader: Info [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntime forwarding xrInitializeLoaderKHR call to runtime after calling xrNegotiateLoaderRuntimeInterface.
	Line 395: 05-31 13:17:27.888 31746 31782 I OpenXR-Loader: Info [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntime succeeded loading runtime defined in manifest file /system/active_runtime.json using interface version 1 and OpenXR API version 1.0
	Line 408: 05-31 13:17:27.888 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Completed loader trampoline
	Line 409: 05-31 13:17:27.888 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Entering loader trampoline
	Line 416: 05-31 13:17:27.888 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Completed loader trampoline
	Line 420: 05-31 13:17:27.888 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrCreateInstance | OpenXR-Loader] : Entering loader trampoline
	Line 421: 05-31 13:17:27.888 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrCreateInstance | OpenXR-Loader] : Entering LoaderInstance::CreateInstance
	Line 422: 05-31 13:17:27.888 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrCreateInstance | OpenXR-Loader] : Entering loader terminator
	Line 1611: 05-31 13:17:28.899 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrCreateInstance | OpenXR-Loader] : Completed loader terminator
	Line 1613: 05-31 13:17:28.899 31746 31782 I OpenXR-Loader: Info [GENERAL | xrCreateInstance | OpenXR-Loader] : LoaderInstance::CreateInstance succeeded with 0 layers enabled and runtime interface - created instance = 0x0000007725e4da80
	Line 1614: 05-31 13:17:28.899 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrCreateInstance | OpenXR-Loader] : Completed loader trampoline
	Line 1623: 05-31 13:17:28.899 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrDestroyInstance | OpenXR-Loader] : Entering loader trampoline
	Line 1624: 05-31 13:17:28.899 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrDestroyInstance | OpenXR-Loader] : Entering loader terminator
	Line 1643: 05-31 13:17:28.909 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrDestroyInstance | OpenXR-Loader] : Completed loader terminator
	Line 1644: 05-31 13:17:28.909 31746 31782 V OpenXR-Loader: Verbose [GENERAL | xrDestroyInstance | OpenXR-Loader] : Completed loader trampoline
	Line 1645: 05-31 13:17:28.909 31746 31782 I OpenXR-Loader: Info [GENERAL | xrDestroyInstance | OpenXR-Loader] : RuntimeInterface::UnloadRuntime - Unloading RuntimeInterface
	Line 1646: 05-31 13:17:28.909 31746 31782 I OpenXR-Loader: Info [GENERAL |  | OpenXR-Loader] : RuntimeInterface being destroyed.
	Line 1650: 05-31 13:17:28.909 31746 31779 V OpenXR_Conformance:     APP_CMD_PAUSE
	Line 2407: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance: Runtime instance properties:
	Line 2408: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:    Runtime name: OplusOpenXR
	Line 2409: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:    Runtime version 0.10.2
	Line 2410: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance: Test options:
	Line 2411: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:    graphicsPlugin: OpenGLES
	Line 2412: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:    formFactor: Hmd
	Line 2413: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:    environmentBlendMode: Opaque
	Line 2414: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:    viewConfiguration: Stereo
	Line 2415: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:    enabledAPILayers:
	Line 2416: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:    enabledInstanceExtensions:
	Line 2417: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:    invalidHandleValidation: no
	Line 2418: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:    fileLineLoggingEnabled: yes
	Line 2419: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:    debugMode: yes
	Line 2420: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance: Available API layers:
	Line 2421: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     <none>
	Line 2422: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance: Available instance extensions:
	Line 2423: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     XR_KHR_android_create_instance, extension version 3
	Line 2424: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     XR_KHR_loader_init, extension version 1
	Line 2425: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     XR_KHR_loader_init_android, extension version 1
	Line 2426: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     XR_KHR_opengl_es_enable, extension version 8
	Line 2427: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     XR_EXT_debug_utils, extension version 4
	Line 2428: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     XR_MND_headless, extension version 2
	Line 2429: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     XR_MND_swapchain_usage_input_attachment_bit, extension version 2
	Line 2430: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     XR_KHR_swapchain_usage_input_attachment_bit, extension version 3
	Line 2431: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     XR_EXTX_overlay, extension version 5
	Line 2432: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     XR_EXT_hand_tracking, extension version 4
	Line 2433: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     XR_FB_swapchain_update_state, extension version 3
	Line 2434: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     XR_FB_foveation, extension version 1
	Line 2435: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance:     XR_FB_foveation_configuration, extension version 1
	Line 2436: 05-31 13:17:29.903 31746 31782 V OpenXR_Conformance: 
	Line 2450: 05-31 13:17:29.904 31746 31779 V OpenXR_Conformance:     APP_CMD_TERM_WINDOW

	**Line 2456: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Unable to open file: '/sdcard/openxr_conformance.xml'**

	Line 2457: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Test initialized
	Line 2458: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: *********************************************
	Line 2459: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Conformance Report
	Line 2460: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: *********************************************
	Line 2461: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Random seed used: 1654003047
	Line 2462: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: API version: 1.0.23
	Line 2463: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Graphics system: OpenGLES
	Line 2464: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Present API layers:
	Line 2465: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance:     <none>
	Line 2466: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Tested instance extensions:
	Line 2467: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance:     XR_KHR_android_create_instance
	Line 2468: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance:     XR_KHR_opengl_es_enable
	Line 2469: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Tested form factor: Hmd
	Line 2470: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Tested view configuration: Stereo
	Line 2471: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Tested environment blend mode: Opaque
	Line 2472: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Handle invalidation tested: no

> 	Line 2473: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Non-disconnectable devices: no
> 	Line 2474: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Test Success Count: 0
> 	Line 2475: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Test Failure Count: 0

	Line 2476: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: Exit Result 0
	Line 2477: 05-31 13:17:29.909 31746 31782 V OpenXR_Conformance: ... end conformance test ...
	Line 2480: 05-31 13:17:29.910 31746 31779 V OpenXR_Conformance:     APP_CMD_STOP
	Line 2485: 05-31 13:17:29.913 31746 31779 V OpenXR_Conformance:     APP_CMD_DESTROY
	Line 2486: 05-31 13:17:29.913 31746 31779 V OpenXR_Conformance: ... calling ANativeActivity_finish ...
	Line 2487: 05-31 13:17:29.913 31746 31779 V OpenXR_Conformance: ... joining test thread ...
	Line 2800: 05-31 13:17:30.336 31746 31779 V OpenXR_Conformance: ... processClass = 0x1
	Line 2801: 05-31 13:17:30.336 31746 31779 V OpenXR_Conformance: ... myPidMethodId = 0x701511f0
	Line 2802: 05-31 13:17:30.336 31746 31779 V OpenXR_Conformance: ... killProcessMethodId = 0x70151178
	Line 2803: 05-31 13:17:30.336 31746 31779 V OpenXR_Conformance: ... pid = 31746

now， I want to know：
(1). if anything that must to be configured before on android platform ? such as the property debug.xr.conform.args
     and what is the correct configured？
(2). I want to export the result to the file “/sdcard/openxr_conformance.xml”， but it seems can not open。
what is the correct configure for the test result output？

I also run the CTS with monado runtime on android platform,  and got the same result above.

**Comment by rpavlik** [comment]
You might need to adjust the output path to be something other than `/sdcard`. And yes, you do need to set debug.xr.conform.args to contain the args you'd otherwise pass on the command line.

**Comment by rpavlik** [comment]
The output path has been changed to the application data folder in 1.0.25.
