### ISSUE TITLE
ahardwarebuffer format not support

### ISSUE THREAD

**Issue by chenxuanyu** [KhronosGroup/OpenXR-CTS#41]
when i run test_xrCreateSwapchain.cpp
the one test item test format VK_FORMAT_D32_SFLOAT_S8_UINT, 
in my service  I use  AHardwareBuffer,there not have AHardwareBuffer formart correspondence to VK_FORMAT_D32_SFLOAT_S8_UINT.
so this test crash. how can I deal with it,did I not use AHardwareBuffer  ?  or just not test it and return sucess ? can you help me ,thanks.

E AdrenoUtils: <validate_memory_layout_input_parmas:2270>: Unknown Format 0
06-12 03:31:01.258  1769  1810 E AdrenoUtils: <adreno_init_memory_layout:5093>: Memory Layout input parameter validation failed!
06-12 03:31:01.258  1769  1810 E qdgralloc: GetGpuResourceSizeAndDimensions Graphics metadata init failed
06-12 03:31:01.258  1769  1810 E Gralloc3: isSupported(2160, 2160, 52, 1, ...) failed with 1
06-12 03:31:01.258   845  1287 E qdgralloc: GetGpuPixelFormat: No map for format: 0x34
06-12 03:31:01.258   845  1287 E AdrenoUtils: <validate_memory_layout_input_parmas:2270>: Unknown Format 0
06-12 03:31:01.258   845  1287 E AdrenoUtils: <adreno_init_memory_layout:5093>: Memory Layout input parameter validation failed!
06-12 03:31:01.258   845  1287 E qdgralloc: GetGpuResourceSizeAndDimensions Graphics metadata init failed

**Comment by chenxuanyu** [comment]
Thanks for the reply，but I am not Khronos members，I can not see the processes，can you share here ，thanks

**Comment by rpavlik** [comment]
I don't think the test hard-requires it, are you advertising that you support that format in xrEnumerateSwapchainFormats ?

**Comment by chenxuanyu** [comment]
no need help,thanks
