### ISSUE TITLE
Conformance test requirements for runtime on hand-held devices

### ISSUE THREAD

**Issue by csn1800** [KhronosGroup/OpenXR-CTS#56]
Hi,

I am looking for a specific detail with respect to the conformance test for OpenXR. 

We may be developing a runtime that supports only the following configuration as per our use cases:
1. XrFormFactor - XR_FORM_FACTOR_HANDHELD_DISPLAY 
2. XrViewConfigurationType - XR_VIEW_CONFIGURATION_TYPE_PRIMARY_MONO 

If so, will it be considered as a conformant OpenXR implementation/runtime? 

In brief, will a runtime be considered as conformant if the implementation support only **hand-held form factor** with **mono view configuration**? It will not be supporting head mounted devices and/or stereo configuration. The purpose of this implementation is to use OpenXR with hand-held device having a single camera.

**Comment by rpavlik** [comment]
If you follow the rest of the adopter process, yes. We've been hoping folks working on mono handheld devices would start implementing it :)

You may need to perform some porting changes to the CTS as we don't have another public mono-handheld device to verify on, see the full Conformance Process Document for details. https://www.khronos.org/files/conformance_procedures.pdf  You can develop and submit your porting changes through a PR on GitHub.

I would definitely encourage you to have your organization join Khronos for more direct participation with the working group. If nothing else, get your Adopter paperwork in soon so you can have a more direct channel to other vendors and folks working on the CTS.

**Comment by rpavlik** [comment]
I checked with the working group and I correctly described things in my earlier comment, so I'll close this for now. Feel free to open pull requests if you find you need to make changes, and/or reach out on the adopter mailing list.
