### ISSUE TITLE
Test cmd do not support add parameters with "nonDisconnectableDevices"

### ISSUE THREAD

**Issue by fukewei** [KhronosGroup/OpenXR-CTS#63]
we run [actions][interactive] test cases on the Android platform, and we want to add parameters with "nonDisconnectableDevices" like following：

adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[actions][interactive],-I,khr/simple_controller" -e hands left -e nonDisconnectableDevices true -e xmlFilename interactive_action_simple_controller.xml

However, we cannot see from the logs or test phenomena that this parameter works.

the log is:"OpenXR_Conformance: Non-disconnectable devices: no"

and the test did not skip the test items related to turn off.

**Comment by johnkearney** [comment]
With how it is written today, nonDisconnectableDevices needs to be in the args. i.e.: `adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[actions][interactive],-I,khr/simple_controller,--nonDisconnectableDevices" -e xmlFilename interactive_action_simple_controller.xml`

**Comment by fukewei** [comment]
Thank you very much for your help. The command you provided effectively solved my problem.
